# Generated by Django 4.1 on 2022-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
