runtime: python39  # Use the Python version suitable for your app
entrypoint: gunicorn -b :$PORT core.wsgi  # Replace 'core' with the correct Django app module

handlers:
  - url: /static
    static_dir: static  # Serve static files from the 'static' folder

  - url: /.*
    script: auto  # Route all other requests to the app
skip_files:
- "*.log"
- "tests/data/*"  # Exclude entire directory with test data
