runtime: python312
env: flex

handlers:
- url: /
  script: main.app

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Optional: If you have static files
# handlers:
# - url: /static
#   static_dir: static
