runtime: python39  # Replace with your desired Python version (e.g., python37)

# Optional for Flexible environment:
env: flex

service:  my-django-app  # Replace with a unique service name

env_variables:
  # Add environment variables securely (see instructions below)
  DATABASE_HOST: "34.28.159.132"
  DATABASE_PORT: "habot"
  DATABASE_NAME: "habot"
  DATABASE_USER: "habot"
  DATABASE_PASSWORD: "123456"
  # ... other environment variables your app needs

handlers:
- url: /.*
  script: manage.py  # Replace with your application's entry point script
